@startuml Sample

interface Iterator {
    hasNext()
    next()
}

interface Aggregate {
    Iterator iterator()
}

class Book {
    String name

    getName()
}

class BookShelf {
    Book[] books
    int last

    getBookAt()
    appendBook()
    getLength()
    Iterator iterator()
}

class BookShelfIterator {
    BookShelf bookShelf
    int index

    hasNext()
    next()
}

Aggregate -> Iterator : Creates

Aggregate <|-- BookShelf : implement

Iterator <|-- BookShelfIterator : implement

BookShelf <-o BookShelfIterator

BookShelf o--> Book

@enduml